# Generated by Django 4.1.10 on 2024-04-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("Depends", "Depends"),
                            ("Suggests", "Suggests"),
                            ("Conflicts", "Conflicts"),
                        ],
                        default="Depends",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("priority", models.CharField(blank=True, max_length=100, null=True)),
                ("section", models.CharField(blank=True, max_length=100, null=True)),
                ("installed_size", models.IntegerField(default=0)),
                ("maintainer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "architecture",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("homepage", models.URLField(blank=True, null=True)),
                (
                    "python_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "dependencies",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        through="dpkg_detailer.Dependency",
                        to="dpkg_detailer.package",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dependency",
            name="depends_on",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_dependencies",
                to="dpkg_detailer.package",
            ),
        ),
        migrations.AddField(
            model_name="dependency",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_dependencies",
                to="dpkg_detailer.package",
            ),
        ),
    ]
